rlf/uSkyBlock

- src/main/java/us/talabrek/ultimateskyblock/handler/WorldGuardHandler.java
fixes https://github.com/rlf/uSkyBlock/issues/107
> vehicle-destroy should not be set

- src/main/resources/challenges.yml
Elaborated on adding multiple permission nodes as rewards.
Elaborated on running commands as OP or from Console.
> Added more info on perm/command rewards

- src/main/java/us/talabrek/ultimateskyblock/command/InviteHandler.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/InviteCommand.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/SetWarpCommand.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/ToggleWarp.java
- src/main/java/us/talabrek/ultimateskyblock/island/IslandInfo.java
Updated names to aqua color were needed to make the messages better looking as a few default messages that weren't pink.
> update messages with color

- src/main/java/us/talabrek/ultimateskyblock/player/PlayerInfo.java
Save the PlayerInfo in updatePlayerInfo only when something has changed.
Issue: https://github.com/rlf/uSkyBlock/issues/353
> Save PlayerInfo only when there are changes.

- .travis.yml
- src/main/java/us/talabrek/ultimateskyblock/SkyBlockMenu.java
> biome added

- src/main/java/us/talabrek/ultimateskyblock/event/PlayerEvents.java
This adds the {uskyblock_island_level} island level chat variable.
> Add an island level chat variable.

- pom.xml
- src/main/java/us/talabrek/ultimateskyblock/command/admin/AbstractAsyncPlayerInfoCommand.java
- src/main/java/us/talabrek/ultimateskyblock/player/PlayerLogic.java
- src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java
- src/main/java/us/talabrek/ultimateskyblock/uuid/PlayerNameChangeManager.java
- Disabled maven creating a useless dependency-reduced-pom.xml
- Enabled maven shade jar minimization.
- Fixed an incorrect call in AbstractAsyncPlayerInfoCommand.
- Fixed user loading.
- Made user loading more reliable.
- Fixed an NPE due to PlayerNameChangeManager getting a bad playerDB instance.
> Improvements and Bug Fixes

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/util/LocationUtil.java
Fixes Guardians not spawning and exceptions beeing thrown when a squid spawns in deep ocean biome.
See Issue #558
> This fixes #558

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/async/IncrementalRunnable.java
> cauldron fix

- uSkyBlock-Core/src/main/po/de.po
Didn't have the time to go through all of them but fixed some of them.
Sometimes it's hard because you don't know what exactly the message is saying(I fully get the written englisch and the sense of it, but it's hard when you don't know what comes before and what after a specific phrase.) and where the message is placed ingame.
In some cases messages seems to appear twice (compared the dutch file lenght with the german file lenght and did see that the german is 400 lines longer)
> Fixed many german translations

- uSkyBlock-Core/src/main/po/ko.po
> Challenges pagination not dependent on translation

- uSkyBlock-Core/src/main/po/de.po
Completed german translation.
There might be still some old phrases that were translated wrong by someone else before.
Didn't check all of them.
> Completed and corrected(most of the old strings) German translation.

- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/nl.po
- uSkyBlock-Core/src/main/resources/challenges.yml
Fixed wrong % value's and changed "take items" to false in "Animalfarm" challenge
> fixed errors in challenges file

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/challenge/Challenge.java
- uSkyBlock-Core/src/main/po/en_GB.po
Small update language file en_GB added space in challenges lore
> Small update language file en_GB added space in challenges lore

- uSkyBlock-Core/src/main/po/en_GB.po
Small update language file en_GB
> Small update language file en_GB

- stop
- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/nl.po
update nl and GB_en language files
Needs a good check plz
> update nl and GB_en language files

- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/nl.po
- uSkyBlock-Core/src/main/resources/challenges.yml
- uSkyBlock-Core/src/main/resources/config.yml
updated nl language
updated en_GB language
updated challenges file Horse to EntityHorse
updated config to explain better the use of the island GUI
> update various files

- uSkyBlock-Core/pom.xml
- uSkyBlock-Core/src/main/po/en2kitteh.pl
- uSkyBlock-Core/src/main/po/lol_US.po
- uSkyBlock-Core/src/main/po/xx_lol_US.po
teh kittehs wants to reed teh messigiz too
> add lolcat localization

- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/vi_VN.po
Vietnamese language added vi_VN
Updated nl.po and en_GB.po to latest keys.pot
> added vi_VN.po + updated nl.po and en_GB.po

- uSkyBlock-Core/src/main/po/vi_VN.po
> final fix for vi_VN

- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/nl.po
> update en_GB.po and nl.po

- uSkyBlock-Core/src/main/po/de.po
This updates the german language file to 2.7
> Updated german language files to 2.7

- uSkyBlock-Core/src/main/po/fr.po
> Updated French language file

- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/nl.po
- uSkyBlock-Core/src/main/resources/challenges.yml
> small challenges correction and .po updates

- uSkyBlock-Core/src/main/po/cs.po
- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/ru.po
cs.po, en_GB and ru.po updated (again)
> cs.po, en_GB and ru.po updated

- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/resources/challenges.yml
Corrected some challenges reward as there was a wrong format for mobs.
Small typo in en_GB fixed.
> corrected some rewards in the challenges, fixed typo in en_GB

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/InviteHandler.java
> corrected previous mistake

- uSkyBlock-Core/src/main/po/de.po
Updates german translation to latest beta
> Updated german translation

- uSkyBlock-Core/src/main/po/en_GB.po
- uSkyBlock-Core/src/main/po/nl.po
- uSkyBlock-Core/src/main/resources/config.yml
Updated config so both island-schemes have the same options listed now.
Small language update to en_GB and NL.
> config updated

- uSkyBlock-Core/src/main/po/it.po
- uSkyBlock-Core/src/main/resources/challenges.yml
Added Italian translation
Updated the challenges file for MC1.11 with IRON_GOLEM:1
> added it.po changed IRON_GOLEM:1

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/NetherTerraFormEvents.java
> 1.11 Fix for Wither Skeletons

- uSkyBlock-Core/src/main/po/it.po
> update Italian language

- ISSUE_TEMPLATE.md
> Updating issue template

- uSkyBlock-Core/src/main/po/en_GB.po
update and improved en_GB language file
> update en_GB language file

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/RegionCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/BiomeCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/AsyncWorldEditHandler.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/ChunkComparator.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldEditHandler.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldGuardHandler.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/task/WorldEditClear.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/task/WorldEditClearFlatlandTask.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/task/WorldEditRegen.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/task/WorldRegen.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/task/ChunkSnapShotTask.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/task/SetBiomeTask.java
- uSkyBlock-Core/src/test/java/us/talabrek/ultimateskyblock/handler/WorldEditHandlerTest.java
> Fixed WorldEdit Vector refactoring

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/completion/OnlinePlayerTabCompleter.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/BanCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/InfoCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/KickCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/LevelCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/WarpCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/ExploitEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/GriefEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/ItemDropEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/PlayerEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/SpawnEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/WorldGuardEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/CooldownHandler.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandInfo.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/SkyBlockMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/player/PlayerLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/player/TeleportLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java
Don't think that it's useful to create a lot of PR's for all (small) changes we make from all the different branches. Pushing them all into my development branch and PR'ing that one.
This commit fixes #1120, only add a target player to the tabcompleter list if the commandsender can see them.
Compiled JAR-file: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20181108-1-61aae59.jar
> WIP: Continuous PR

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/MultiverseCoreHandler.java
Fixes #1125 
Pre-compiled JAR: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20181108-2-500b816.jar
> Set spawnAdjust to false when adding a world to MV

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/GotoIslandCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/BanCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/KickCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/LeaveCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/SpawnCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/PlayerEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/player/PlayerLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java
> Purge old island and playerinfo when using /usb island register (#948)

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldEditHandler.java
It was never correct to remove players and since https://github.com/PaperMC/Paper/commit/28cf2696d4078643774b896fb6a9dcda0a35a8fd it will cause an exception when trying
> Do not remove players from the world when resetting islands

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldGuardHandler.java
> Change nether max Y to 120 (#1172)

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java
- uSkyBlock-FAWE/pom.xml
- uSkyBlock-FAWE/src/main/java/us/talabrek/ultimateskyblock/handler/asyncworldedit/FAWEAdaptor.java
Hacky workaround for #1169 for the moment.
> Don't check WorldEdit version if FAWE is present

- uSkyBlock-API/pom.xml
> Publish uSkyBlock-API artifacts to repository (#1137)

- uSkyBlock-API/pom.xml
- uSkyBlock-Core/pom.xml
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/ChunkCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/MenuEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/WorldEditHandler.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/IntegerEditMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/MainConfigMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/SkyBlockMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/StringEditMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/player/UltimateHolder.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/signs/SignEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/signs/SignLogic.java
Improved version of #1173, without using any dependency at all.
Will add more fixes eventually.
If you have any further improvements, problems or anything else, feel free to ask and I will try my best to fix that.
This PR should remain compatibility with 1.13 (not tested, but I am pretty sure)
> Fixes for 1.14

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/AdminIslandCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/CooldownCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/BanCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/InviteCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/TrustCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/ItemDropEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/WorldGuardEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/AsyncWorldEditHandler.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/imports/wolfwork/PlayerInfo.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/mojang/MojangAPI.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/util/ServerUtil.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uuid/BukkitPlayerDB.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uuid/FilePlayerDB.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uuid/MemoryPlayerDB.java
Just starting at the top of the warnings list in my IDE to check off things. Going to PR (+squash and merge) this separately before doing some API changes.
> Small deprecation fixes #1

- .travis.yml
- pom.xml
- uSkyBlock-Core/pom.xml
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/placeholder/MVdWPlaceholderAPI.java
- uSkyBlock-Plugin/pom.xml
Fixes #1170 
DeluxeChat is something to look into later.
> Fix MVdWPlaceholderAPI implementation

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandGenerator.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/util/FileUtil.java
- uSkyBlock-Core/src/test/java/us/talabrek/ultimateskyblock/util/FileUtilTest.java
> Accept schematics ending in .schem (#1207)

- uSkyBlock-Core/pom.xml
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/chat/ChatEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/SkyBlockMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/signs/SignEvents.java
Fixed shift clicking items into menus from your inventory, island chat not working and challenge signs not working
> A few fixes

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/PlayerEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/SpawnEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/IntegerEditMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/MainConfigMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/StringEditMenu.java
should also fix https://github.com/rlf/uSkyBlock/issues/1206
> Fixes a few things

- uSkyBlock-Core/src/main/po/fr.po
Quick fix for french translation.
> Fix french translation

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/SpawnEvents.java
- uSkyBlock-Core/src/main/resources/config.yml
- uSkyBlock-Core/src/test/java/us/talabrek/ultimateskyblock/event/SpawnEventsTest.java
> Control Phantom spawning via config setting (#1219)

- pom.xml
- uSkyBlock-AWE370/README.md
- uSkyBlock-AWE370/pom.xml
- uSkyBlock-AWE370/src/main/java/us/talabrek/ultimateskyblock/handler/asyncworldedit/AWE370Adaptor.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/AsyncWorldEditHandler.java
- uSkyBlock-Plugin/pom.xml
- uSkyBlock-Plugin/src/assembly/plugin.xml
> Re-add Asyncworldedit support

- uSkyBlock-Core/src/main/po/de.po
hi!
i just made some small changes to the de.po file.
if this gets accepted, i'm probably going to make more changes to the file in the future.
thx
> small german language update (de.po)
