rlf/uSkyBlock

- src/main/java/us/talabrek/ultimateskyblock/event/PlayerEvents.java
I grabbed the method to get the island info from a location from your AbstractIslandInfoCommand class as well as the deny message from your warp command class.
> Prevent players from bypassing island bans on teleport. Resolves #271.

- src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java
Since my world predates use of worldguard, and I'm not yet ready to trust purge, I needed the 'islandAtLocation' routine to check more thoroughly for an existing island. This version requires both no worldguard region at the location, and no bedrock in the surrounding vicinity. I also increased the Y swing for  the 'findBedrockLocation'call to account for the change in default height configuration which escaped me for a while.
> fix for issue  #183

- src/main/java/us/talabrek/ultimateskyblock/command/admin/task/PurgeScanTask.java
This is probably system dependent or you'd have caught it, but on mine purge will delete all the islands older than 1 day, no matter how many days I tell it. Calculates correctly if I force a long in there.
> fix integer overflow on purge cutoff calculation

- src/main/java/us/talabrek/ultimateskyblock/command/InviteHandler.java
- src/main/java/us/talabrek/ultimateskyblock/command/admin/CooldownCommand.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/KickCommand.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/PartyCommand.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/TrustCommand.java
- src/main/java/us/talabrek/ultimateskyblock/island/IslandInfo.java
This pull request fixes the main-threaded UUID lookups the plugin does by using getOfflinePlayer().
Reason:
These UUID lookups cause TPS drops, and can occasionally even crash the server.
Cause:
getOfflinePlayer() in CraftServer will do a UUID lookup if the server is in online-mode and the players profile cannot be found.
Reason for each file change:
* src/main/java/us/talabrek/ultimateskyblock/command/InviteHandler.java
* This stores the players name along with the UUID now when a player is invited, used in one of the other changes.
* src/main/java/us/talabrek/ultimateskyblock/command/admin/CooldownCommand.java
* This before did a UUID lookup when an argument was presented, fixed with a asynchronus callback.
*  src/main/java/us/talabrek/ultimateskyblock/command/island/KickCommand.java
* …
> Fix mainthreaded Mojang API UUID lookups.

- src/main/java/us/talabrek/ultimateskyblock/command/admin/GotoIslandCommand.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/CreateCommand.java
- src/main/java/us/talabrek/ultimateskyblock/command/island/RestartCommand.java
- src/main/java/us/talabrek/ultimateskyblock/handler/task/WorldEditClearTask.java
- src/main/java/us/talabrek/ultimateskyblock/handler/task/WorldEditRegenTask.java
- src/main/java/us/talabrek/ultimateskyblock/handler/worldedit/WorldEdit6Adaptor.java
- src/main/java/us/talabrek/ultimateskyblock/island/IslandGenerator.java
- src/main/java/us/talabrek/ultimateskyblock/island/IslandLogic.java
- src/main/java/us/talabrek/ultimateskyblock/player/PlayerInfo.java
- src/main/java/us/talabrek/ultimateskyblock/player/PlayerLogic.java
- src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java
- src/main/resources/config.yml
This changes the following:
* Prevents concurrent island creates/restarts.
* Load chunks before teleporting a player to prevent visual glitches
* Skips physics updates when setting blocks to reduce tps lag
(EditSession#FastMode, setTypeIdAndData(x, x, false). Shows major
improvements to server performance.
* Adds delay to teleporting the player when creating an island, had
//TODO: Later in the notes.
* Teleports a player to spawn if they logged out in the sky world
without an island.
* Removes a redundant(and breaking) isFlying() check that prevented
players that were flying from being teleport to spawn on island restart.
Many servers allow players to fly with donation perks.
> Improvements

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/PlayerEvents.java
Instead of just now allowing the user to convert obsidian into lava when they have more than one bucket, the code accommodates the stack.
> Allow Multiple Buckets for Obsidian Conversion

- uSkyBlock-Core/src/main/resources/plugin.yml
Removed usb.donor.* and usb.extra.*. These shouldn't be grouped as they need to be given individual. (Probably caused the hunger reduction issue in #895 )
Set all biomes to default false (except Ocean), Op's should not be able to swap biomes without permissions.
Some "bonus permissions" were forgotten to set as default false. (moved some in the list of order to have reward bonuses and extraItems  together)
> plugin.yml updated

- uSkyBlock-Core/src/main/resources/challenges.yml
This fixes this challenge. MushroomCow is the correct name.
It's 1.10 compatible, not sure about 1.8/.19
> Fix "top chef" challenge

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/SkyBlockMenu.java
To keep things consistent, it makes more sense to use `performCommand` for going back to the main menu than actually calling the `displayIslandGUI` method. Also this allows developers to intercept the command and do various things when it's executed.
> Use performCommand instead of openInventory

- pom.xml
- uSkyBlock-API/pom.xml
- uSkyBlock-API/src/main/java/us/talabrek/ultimateskyblock/api/event/IslandLeaderChangedEvent.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/api/event/EventLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/admin/MakeLeaderCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/MakeLeaderCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandInfo.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java
Closes #1088. Bumps the API version to 2.7.5 to introduce a new event.
Adds the requested event for now, I'm thinking of some other refactoring around this code, but that's a todo for later, just like the rest of refactoring. Should at least satisfy the user requesting this feature. 
When trying to build, see: https://github.com/rlf/uSkyBlock/issues/1131
Simple plugin to test this event: https://github.com/Muspah/USBTestListener
Trying to prevent getting lots of logic-classes in main class, but that's something to refactor later, as mentioned.
> Add IslandLeaderChangedEvent, move event firing to seperate class

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/SkyBlockMenu.java
Change the default setting for the island biome change 'window' in the GUI to 'all', fixes #1133.
Tried to fix the deprecated calls to SkullMeta#setOwner(String), but the new API to use requires an OfflinePlayer-object. Getting an OfflinePlayer-instance for a player not in the cache (like an offline island member) may take a few seconds as it calls the Mojang API. That's something we need to think about in the future, maybe look at something like EssentialsX and how they've implemented it in the /skull command. But that's not a priority for now.
> Change the default biome radius in GUI to whole island (#1133)

- uSkyBlock-Core/src/main/po/fr.po
- Fix inconsistency of usage of T-V distinction in french (see https://en.wikipedia.org/wiki/T%E2%80%93V_distinction#French_2 ).
- Fix some mistranslated sentences and words.
- Added more translation
>  Fix french translation

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/NetherTerraFormEvents.java
If you terraform something you can break with your hand such as glowstone, its a bit insane.
> Fixed terraforming without tools.

- pom.xml
- uSkyBlock-API/pom.xml
- uSkyBlock-Core/pom.xml
Updating bStats (+repository URL) and removing some old WE5/6 and Bukkit 1.12 profiles from the POM files. The AWE repository URL is also outdated but re-adding or removing AWE support is another subject.
> Small POM updates

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandLogic.java
- uSkyBlock-Core/src/main/po/keys.pot
Add links to `/is top` command to (partly) fixes #493. click on island name will warp the player to the island, same as `/is warp xx` command
> Add links to /is top command - #493

- pom.xml
- scripts/deploy.sh
- uSkyBlock-API/pom.xml
- uSkyBlock-API/src/main/java/us/talabrek/ultimateskyblock/api/IslandInfo.java
- uSkyBlock-API/src/main/java/us/talabrek/ultimateskyblock/api/event/island/IslandBanPlayerEvent.java
- uSkyBlock-API/src/main/java/us/talabrek/ultimateskyblock/api/event/island/IslandUnbanPlayerEvent.java
- uSkyBlock-Core/pom.xml
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/BanCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/command/island/TrustCommand.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandInfo.java
- uSkyBlock-FAWE/pom.xml
- uSkyBlock-Plugin/pom.xml
Removing the api-function IslandInfo#isBanned(Player player) can be done in the next change, because IslandInfo#isBanned(OfflinePlayer target) should cover it (Player implements OfflinePlayer).
See PR #1187 for the reasoning behind using OfflinePlayer instead of using UUID objects.
Made these changes while on the road, so there are a few things to take into consideration when following-up on this:
1) Save the API-version we're implementing in USB-Core somewhere, so we can report the actual version we're implementing to other plugins calling for the API;
2) Deprecate all API functions in uSkyBlock's main class except for a new/improved getApi() method.
These new events and methods aren't _really_ useful for external plugins at the moment, but they should work as described (tested locally) …
> Add island ban-related events to API

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandInfo.java
isTrusted will always return false since it didnt compare the targets UUID
> Fixed /is trust

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/world/ChunkRegenerator.java
- uSkyBlock-Core/src/main/resources/config.yml
Fixes #1217 
Added a config option to change the chunk regenerator speed.
Should also fix an issue reported on the SpigotMC forums where the starter chest gets filled up with the items multiple times.
> Break out for loop in ChunkGenerator when chunkList is empty (#1217)

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/event/MenuEvents.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/IntegerEditMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/MainConfigMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/SkyBlockMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/menu/StringEditMenu.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/player/UltimateHolder.java
- uSkyBlock-Core/src/test/java/us/talabrek/ultimateskyblock/event/MenuEventsTest.java
Adds a MenuType enum to UltimateHolder and chooses the right menu type based on that value, instead of matching parts of the title.
Should also fix #1102 as far as I can see, but I'm unable to test with the mentioned permission plugin because it's a paid resource.
> Add MenuType to UltimateHolder

- uSkyBlock-Core/src/main/resources/challenges.yml
The reward text was saying 2 lapis, but the actual reward was 2 ink sac
> Fisherman’s repeated challenge rewarded 2 INK_SAC instead of 2 LAPIS_LAZULI

- uSkyBlock-Core/src/main/resources/challenges.yml
Some block ids were duplicated after conversion of this file from pre1.13 to 1.13.
I used the informations that was in the file before the changes was made (old ids and comments) to deduce the proper item id : https://github.com/rlf/uSkyBlock/commit/3637195fd9cadd63040ee6da4f755ddd2033d7e1#diff-59b62696817efec79c5b22d696ade632L1178
> Fix duplicated requiredItems in challenges tajmahal and greatpyramid

- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/Settings.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandLocatorLogic.java
- uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/world/SkyBlockChunkGenerator.java
- uSkyBlock-Core/src/main/resources/config.yml
It was A Long Way To Tipperary...
I am requesting to made a more flexible method to populate newly created islands.
**The aims of this pull:**
- to set the SkyBlock origin to (orgx,orgz)
- to set the quadrants where new islands are about to be deployed
Therefore I have introduced new settings in config.yml 
under the island section as follows:
```
orgx: 0
orgz: 0
path: UNI
```
The support code to implement these features are included.
(in Settings and IslandLocatorLogic)
**Background:**
I'd like to create a SkyWorld with prefilled regions and a living SkyBlock.
Those are:
Northern hemisphere - SkyGrid with tons of secrets
Spawn region with a Sky City (nowadays CityWorld)
South-Eastern region with ancient dead SkyBlocks and SkyLands
South-West: the new living SkyBlock
**Notes:**
1. Do not …
> NewIslandLocatorLogic

- pom.xml
- uSkyBlock-API/pom.xml
- uSkyBlock-Core/pom.xml
- uSkyBlock-FAWE/pom.xml
It worked on my machine... :/
Since the new 1.16.1 API is only available as org.spigotmc:spigot-api, old Bukkit versions from our dependencies are sometimes used when building. Every old Bukkit dependency should be excluded now. The exclusion rules can be removed in the future when developers switch to spigot-api.
> Dependency horror on 1.16

- uSkyBlock-Core/src/main/resources/challenges.yml
presumably 1.12 migration error (322:0:1 should be golden_apple, not lapis_block).
> topchef requires GOLDEN_APPLE instead of LAPIS_BLOCK
